apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-config
data:
  feature_store.yaml: |
    project: default
    registry:
      registry_type: file
      path: /feast/registry.db
    provider: local
    online_store:
      type: redis
      connection_string: redis:6379
    offline_store:
      type: file