apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-server
  labels:
    app: feast-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-server
  template:
    metadata:
      labels:
        app: feast-server
    spec:
      containers:
      - name: feast-server
        image: feastdev/feature-server:latest
        ports:
        - containerPort: 6566
        env:
        - name: FEAST_CORE_URL
          value: "localhost:6566"
        volumeMounts:
        - name: feast-config
          mountPath: /feast
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: feast-config
        configMap:
          name: feast-config