apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-server
  labels:
    app: feast-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-server
  template:
    metadata:
      labels:
        app: feast-server
    spec:
      initContainers:
      - name: feast-apply
        image: feastdev/feature-server:latest
        command: ["feast", "apply"]
        workingDir: /feast
        volumeMounts:
        - name: feast-storage
          mountPath: /feast
        - name: feast-config
          mountPath: /feast/feature_store.yaml
          subPath: feature_store.yaml
      containers:
      - name: feast-server
        image: feastdev/feature-server:latest
        ports:
        - containerPort: 6566
        command: ["feast", "serve"]
        workingDir: /feast
        volumeMounts:
        - name: feast-storage
          mountPath: /feast
        - name: feast-config
          mountPath: /feast/feature_store.yaml
          subPath: feature_store.yaml
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: feast-storage
        emptyDir: {}
      - name: feast-config
        configMap:
          name: feast-config