apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite
  labels:
    app: sqlite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite
  template:
    metadata:
      labels:
        app: sqlite
    spec:
      containers:
      - name: sqlite
        image: nouchka/sqlite3:latest
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: sqlite-storage
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: sqlite-storage
        emptyDir: {}