apiVersion: v1
kind: Service
metadata:
  name: fti-predict-learn-service
  labels:
    app: fti-predict-learn
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
  selector:
    app: fti-predict-learn