
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: online-learning-pipeline-v2
  namespace: argo
spec:
  entrypoint: online-learning-dag

  volumeClaimTemplates:
  - metadata:
      name: repo-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: online-learning-dag
    dag:
      tasks:
        - name: clone-repo
          template: clone-git-repo
        - name: ingest-data
          template: get-data
          dependencies: [clone-repo]
        - name: generate-features
          template: run-feature-generation
          dependencies: [ingest-data]
          arguments:
            artifacts:
              - name: raw-data
                from: "{{tasks.ingest-data.outputs.artifacts.data-artifact}}"
        - name: predict-learn
          template: run-prediction
          dependencies: [generate-features]
          arguments:
            artifacts:
              - name: features-data
                from: "{{tasks.generate-features.outputs.artifacts.features-artifact}}"

  - name: clone-git-repo
    container:
      image: alpine/git:latest
      command: [git, clone, "https://github.com/r0d3r1ch25/online_learning.git", /src]
      volumeMounts:
        - name: repo-storage
          mountPath: /src

  - name: get-data
    container:
      image: alpine:latest
      command: ["sh", "-c"]
      args: ["cp /src/pipelines/ingestion_service/data.csv /tmp/data.csv"]
      volumeMounts:
        - name: repo-storage
          mountPath: /src
    outputs:
      artifacts:
        - name: data-artifact
          path: /tmp/data.csv

  - name: run-feature-generation
    inputs:
      artifacts:
        - name: raw-data
          path: /tmp/data.csv
    outputs:
      artifacts:
        - name: features-artifact
          path: /tmp/features.json
    container:
      image: python:3.9-slim
      command: [sh, -c]
      args:
        - |
          pip install pandas requests
          python -u /src/infra/argo/v2/feature_generator.py
      volumeMounts:
        - name: repo-storage
          mountPath: /src

  - name: run-prediction
    inputs:
      artifacts:
        - name: features-data
          path: /tmp/features.json
    container:
      image: python:3.9-slim
      command: [sh, -c]
      args:
        - |
          pip install pandas requests
          python -u /src/infra/argo/v2/predictor.py
      volumeMounts:
        - name: repo-storage
          mountPath: /src
