
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: online-learning-pipeline-v2
  namespace: argo
spec:
  entrypoint: online-learning-dag

  templates:
    - name: online-learning-dag
      dag:
        tasks:
          - name: generate-features
            template: run-feature-generation
          - name: predict-learn
            template: run-prediction
            dependencies: [generate-features]
            arguments:
              artifacts:
                - name: features-data
                  from: "{{tasks.generate-features.outputs.artifacts.features-artifact}}"

    - name: run-feature-generation
      outputs:
        artifacts:
          - name: features-artifact
            path: /tmp/features.json
      script:
        image: python:3.9-slim
        command: [sh, -c]
        source: |
          pip install pandas requests
          cp /src/pipelines/ingestion_service/data.csv /tmp/data.csv
          python /src/infra/argo/v2/prime_and_generate.py
        volumeMounts:
        - name: repo
          mountPath: /src
      inputs:
        artifacts:
          - name: repo
            path: /src
            git:
              repo: https://github.com/r0d3r1ch25/online_learning.git
              branch: main

    - name: run-prediction
      inputs:
        artifacts:
          - name: features-data
            path: /tmp/features.json
          - name: repo
            path: /src
            git:
              repo: https://github.com/r0d3r1ch25/online_learning.git
              branch: main
      script:
        image: python:3.9-slim
        command: [sh, -c]
        source: |
          pip install pandas requests
          python /src/infra/argo/v2/batch_predict.py
