apiVersion: v1
kind: Service
metadata:
  name: coinbase-service
  namespace: ml-services
spec:
  type: LoadBalancer
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
  selector:
    app: coinbase-service