apiVersion: v1
kind: Service
metadata:
  name: feature-service
  labels:
    app: feature-service
spec:
  type: LoadBalancer
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: feature-service