apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service
spec:
  type: LoadBalancer
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
  selector:
    app: ingestion-service