{
 "title": "Model Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Actuals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ml_model_last_actual{model=\"linear_regression\"}"
    },
    { "expr": "ml_model_last_prediction" }
   ]
  },
  {
   "title": "Predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ml_model_last_prediction" }
   ]
  },
  {
   "title": "MAPE (Window=5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ml_model_mape_5" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "ml_model_last_error" }
   ]
  }
 ]
}