apiVersion: v1
kind: Service
metadata:
  name: fti-features-service
  labels:
    app: fti-features
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30090
  selector:
    app: fti-features