{
 "title": "Model Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Predictions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(ml_model_last_prediction{model=~\"knn_regressor|amf_regressor|linear_regression\"})",
     "legendFormat": "Ensemble"
    },
    {
     "expr": "ml_model_last_actual{model=\"linear_regression\"}",
     "legendFormat": "Actual"
    }
   ]
  },
  {
   "title": "Predictions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ml_model_last_prediction" },
    {
     "expr": "ml_model_last_actual{model=\"linear_regression\"}"
    }
   ]
  },
  {
   "title": "MAPE (Window=5)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "ml_model_mape_5" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "ml_model_last_error" }
   ]
  }
 ]
}