apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'ml-model-service'
        static_configs:
          - targets: ['model-service.ml-services.svc.cluster.local:8000']
        metrics_path: '/metrics/prometheus'
        scrape_interval: 30s
        scrape_timeout: 10s