apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-service
  labels:
    app: feature-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-service
  template:
    metadata:
      labels:
        app: feature-service
    spec:
      containers:
      - name: feature-service
        image: r0d3r1ch25/ml-features:latest
        ports:
        - containerPort: 8001
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8001"
        - name: N_LAGS
          value: "15"
        - name: REDIS_HOST
          value: "redis.ml-services.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 30