apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-linear
  labels:
    app: model-service-linear
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service-linear
  template:
    metadata:
      labels:
        app: model-service-linear
    spec:
      containers:
      - name: model-service-linear
        image: r0d3r1ch25/ml-model:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_NAME
          value: "linear_regression"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: MODEL_NAME
          value: "linear_regression"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 60