apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-v1
  namespace: argo
spec:
  schedule: "* * * * *"  # Every minute (standard 5-field cron format)
  timezone: "UTC"
  startingDeadlineSeconds: 90
  concurrencyPolicy: Forbid  # Prevent concurrent runs
  successfulJobsHistoryLimit: 20  # Keep last 25 successful workflows
  failedJobsHistoryLimit: 5       # Keep last 5 failed workflows
  workflowSpec:
    entrypoint: e2e-pipeline
    templates:
    - name: e2e-pipeline
      container:
        image: r0d3r1ch25/ml-e2e-job:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "pipeline.py"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"