
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: online-learning-pipeline
  namespace: argo # Ensure this is the namespace where you run Argo Workflows
spec:
  entrypoint: online-learning-workflow
  

  templates:
  - name: online-learning-workflow
    steps:
    - - name: run-simulation
        template: run-online-learning-script

  - name: run-online-learning-script
    # This template defines a container that will run our script.
    inputs:
      artifacts:
      - name: repo
        path: /src
        git:
          # IMPORTANT: Replace this with the URL of your Git repository.
          repo: "https://github.com/r0d3r1ch25/online_learning.git"
          branch: main
    container:
      image: python:3.9-slim
      command: [sh, -c]
      args:
        - |
          pip install pandas requests
          python infra/argo/v1/run_pipeline.py
      workingDir: /src
