name: Coinbase Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'pipelines/coinbase_service/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd pipelines/coinbase_service
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd pipelines/coinbase_service
        PYTHONPATH=. pytest tests/ -v
    
    - name: Build Docker image
      run: |
        cd pipelines/coinbase_service
        docker build -t ml-coinbase:test .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push to Docker Hub
      run: |
        cd pipelines/coinbase_service
        docker build -t r0d3r1ch25/ml-coinbase:latest .
        docker push r0d3r1ch25/ml-coinbase:latest