name: Features CI

on:
  push:
    branches: [ main ]
    paths:
      - 'pipelines/feature_service/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pipelines/feature_service/requirements.txt
    
    - name: Run tests
      env:
        N_LAGS: "10"
      run: |
        cd pipelines/feature_service
        PYTHONPATH=. pytest tests/ -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push feature service
      uses: docker/build-push-action@v5
      with:
        context: ./pipelines/feature_service
        platforms: linux/arm64
        push: true
        tags: r0d3r1ch25/ml-features:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max