name: Model CI

on:
  push:
   branches:
    - main
  workflow_dispatch:  # Manual trigger only

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pipelines/model_service/requirements.txt
    
    - name: Run tests
      run: |
        cd pipelines/model_service
        PYTHONPATH=. pytest tests/ -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push model service
      uses: docker/build-push-action@v5
      with:
        context: ./pipelines/model_service
        platforms: linux/arm64
        push: true
        tags: r0d3r1ch25/fti_model:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max